// vue/src/components/common/Header.vue
<template>
  <div>
    <header>
      <div class="left">
        <img :src="avatar" @click="uploadHeadImg">
        <input
          type="file"
          accept="image/*"
          capture="camcorder"
          @change="handleFile"
          class="hiddenInput"
          style="display: none;"
        >
        <h2>李洋的管理后台</h2>
      </div>
      <div class="right">
        <el-dropdown trigger="click" @command="handleCommand">
          <span class="el-dropdown-link">
            {{userInfo.nickName}}
            <i class="el-icon-arrow-down el-icon--right"></i>
          </span>
          <el-dropdown-menu slot="dropdown">
            <el-dropdown-item command="a">退出登录</el-dropdown-item>
            <el-dropdown-item command="b">修改密码</el-dropdown-item>
          </el-dropdown-menu>
        </el-dropdown>
      </div>
    </header>
    <v-slider></v-slider>
    <div class="tags_box">
      <v-tags></v-tags>
    </div>
    <router-view></router-view>
  </div>
</template>

<script>
import vSlider from "./slider";
import vTags from "./tags";
export default {
  data() {
    return {
      avatar: "http://localhost:3000/img",
      userInfo: ""
    };
  },
  components: {
    vSlider,
    vTags
  },
  methods: {
    handleCommand(command) {
      switch (command) {
        case "a":
          this.quit();
          break;
        case "b":
          this.$router.push({
            name: "userInfo"
          });
          break;
        default:
          break;
      }
    },
    // 退出登录
    quit() {
      let data = {};
      this.$getData("users/quit", data, "post", res => {
        if (res.data.code == 1) {
          this.$message({
            message: res.data.msg,
            type: "success"
          });
          this.$router.push("login");
          sessionStorage.clear();
        } else {
          this.$message({
            message: res.data.msg,
            type: "error"
          });
        }
      });
    },
    //获取用户信息
    getUserInfo() {
      let data = {
        userId: sessionStorage.getItem("userId")
      };
      this.$getData("users/index", data, "post", res => {
        //console.log(res);
        if (res.data.code == 1) {
          this.userInfo = res.data.data;
          this.avatar = "http://localhost:3000/img/" + this.userInfo.headSrc;
          //this.avatar = "http://120.77.220.216:3000/img/" + this.userInfo.headSrc;
        } else {
          this.$message({
            message: res.data.msg,
            type: "error"
          });
          this.$router.push("login");
        }
      });
    },
    uploadHeadImg() {
      //是获取文档中 class=”hiddenInput” 的元素。
      this.$el.querySelector(".hiddenInput").click();
    },
    handleFile(e) {
      let file = e.target.files[0];
      let form = new FormData();
      form.append("myfile", file);
      form.set("userId", sessionStorage.getItem("userId"));
      let data = form;
      // console.log(data);
      this.$getData("/users/changeheadSrc", data, "post", res => {
        if (res.data.code == 1) {
          this.$message({
            message: res.data.msg,
            type: "success"
          });
          this.avatar = "http://localhost:3000/img/" + res.data.headSrc;
        } else {
          this.$message({
            message: res.data.msg,
            type: "error"
          });
        }
      });
    }
  },
  mounted: function() {
    this.getUserInfo();
  }
};
</script>

<style scoped="scoped">
header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  width: 100%;
  height: 80px;
  background-color: rgba(0, 0, 0, 0.25);
}

header .left {
  display: flex;
  flex-direction: row;
}

header .left img {
  width: 60px;
  height: auto;
  padding: 10px;
}

header .left h2 {
  color: #f5f5f5;
  line-height: 80px;
}

header .right {
  margin-right: 300px;
}

header .right span {
  color: #f5f5f5;
  line-height: 80px;
  font-size: 20px;
}

.tags_box {
  margin-left: 220px;
  margin-top: 20px;
}
</style>

// angular7/src/app/component/header/header.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
// 导入路由模块
import { Router, NavigationExtras } from '@angular/router';
// 导入请求数据的服务
import { AxiosService } from '../../service/axios.service';
// 导入element消息提示服务
import { ElMessageService } from 'element-angular';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  @ViewChild('hiddenInput') hiddenInput: any;
  public navIndex: any = '1';
  public userInfo: any = '';
  public asideTo: any = this.router.config[0].children;
  public avatar: any = 'http://localhost:3000/img';
  constructor(public router: Router, public axios: AxiosService, private message: ElMessageService) { }

  ngOnInit() {
    this.getUserInfo();
    // console.log(this.asideTo);
    //  阻止页面刷新的bug
    for (let index = 0; index < this.asideTo.length; index++) {
      // console.log(this.router.url.slice(13, 21));
      // console.log(this.asideTo[index].path);
      if (this.router.url.slice(8, 20) == this.asideTo[index].path) {
        this.navIndex = index.toString();
      } else if (this.router.url.slice(8, 12) == this.asideTo[index].path) {
        this.navIndex = index.toString();
      };
    }
  }
  // 获取账号信息
  getUserInfo() {
    let data: object = {
      userId: localStorage.getItem('userId')
    };
    let result: any = this.axios.$postData('users/index', data);
    result.subscribe((res: any) => {
      // console.log(res);
      if (res.code == 1) {
        this.userInfo = res.data;
        this.avatar = 'http://localhost:3000/img/' + this.userInfo.headSrc;
      } else {
        this.message['error'](res.msg);
      }
    });
  }
  // 退出登录
  quit() {
    let data: object = {};
    let result: any = this.axios.$postData('users/quit', data);
    result.subscribe((res: any) => {
      // console.log(res);
      if (res.code == 1) {
        this.router.navigate(['login']);
        this.message['success'](res.msg);
      }
    });
  }
  uploadHeadImg() {
    // 打开文件选择框
    // let hiddenInput: any = document.getElementsByClassName('hiddenInput')[0];
    // console.log(this.hiddenInput);
    this.hiddenInput.nativeElement.click();
  }
  handleFile(e) {
    let file: any = e.target.files[0];
    let form: any = new FormData();
    form.append('myfile', file);
    form.set('userId', localStorage.getItem('userId'));
    let data: any = form;
    let result: any = this.axios.$postData('users/changeheadSrc', data);
    result.subscribe((res: any) => {
      //  console.log(res);
      if (res.code == 1) {
        this.message['success'](res.msg);
        this.avatar = 'http://localhost:3000/img/' + res.headSrc;
      } else {
        this.message['error'](res.msg);
      }
    });

  }
  handle(index: string): void {
    switch (index) {
      case '0':
        this.router.navigate(['header/weilcome']);
        break;
      case '1':
        this.router.navigate(['header/home']);
        break;
      case '2':
        this.router.navigate(['header/shop']);
        break;
      case '3':
        this.router.navigate(['header/setting']);
        break;
      case '9':
        this.quit();
        break;
      default:
        break;
    }
  }
}

<nav>
    <el-menu [model]="navIndex" (modelChange)="handle($event)" class="el-menu-demo" mode="horizontal" background-color="#545c64"
        active-text-color="#ffd04b" text-color="#fff">
        <el-menu-item>
            <div class="userInfo_box">
                <img [src]="avatar" (click)="uploadHeadImg()">
                <input type="file" accept="image/*" capture="camcorder" (change)="handleFile($event)" #hiddenInput
                    class="hiddenInput" style="display: none;"> {{userInfo.nickName}}
            </div>
        </el-menu-item>
        <el-menu-item index="0">欢迎页</el-menu-item>
        <el-menu-item index="1">用户管理</el-menu-item>
        <el-menu-item index="2">商品管理</el-menu-item>
        <el-menu-item index="3">账号设置</el-menu-item>
        <el-menu-item index="9">退出</el-menu-item>
    </el-menu>
</nav>

<router-outlet></router-outlet>
