// angular7/src/app/component/common/dialog/dialog.component.ts
import { Component, OnInit, Input } from '@angular/core';
// 导入请求数据的服务
import { AxiosService } from '../../../service/axios.service';
// 导入兄弟组件通信服务
import { BortherService } from '../../../service/borther.service';
// 导入element消息提示服务
import { ElMessageService } from 'element-angular';
// 导入强制刷新视图服务



@Component({
  selector: 'app-dialog',
  templateUrl: './dialog.component.html',
  styleUrls: ['./dialog.component.css']
})
export class DialogComponent implements OnInit {
  @Input() getUserList: any;
  @Input() Page: any;
  // 用户id
  public userId: any = localStorage.getItem('userId');
  public userInfo: object = {};
  public isShow: number = 0;
  public fromData: any = {
    userName: '',
    nickName: '',
    loginPass: '',
    email: '',
    sex: '',
    power: ''
  };
  constructor(public axios: AxiosService, public message: ElMessageService, public borther: BortherService) { }

  ngOnInit() {
    this.getUserList();
    // 判断兄弟组件数据变化
    this.borther.eventEmit.subscribe((value: any) => {
      // console.log(value)
      if (value.msg == 2) {
        // 这里就可以操作数据
        this.fromData = value;
        this.open(value.msg);
      }
    });
  }
  // 关闭弹窗
  colse(e) {
    // console.log(e.target.className);
    // 从这里可以看出ng-if指令会帮dom绑定类名
    if (e.target.className == 'alert_warp ng-star-inserted') {
      this.isShow = 0;
    }
  }
  // 开启弹窗
  open(id) {
    id == 1 ? this.fromData = {} : '';
    let result: any = this.borther.openAlert(id);
    result.subscribe((res: any) => {
      this.isShow = res;
      // console.log(this.isShow);
    });
  }
  // 添加管理员
  addUser() {
    let data: object = {
      userId: localStorage.getItem('userId'),
      userName: this.fromData.userName,
      sex: this.fromData.sex,
      nickName: this.fromData.nickName,
      loginPass: this.fromData.loginPass,
      email: this.fromData.email,
      power: this.fromData.power
    };
    // console.log(data);
    let result: any = this.axios.$postData('/index/userlist/add', data);
    result.subscribe((res: any) => {
      if (res.code == 1) {
        this.getUserList();
        this.message['success'](res.msg);
        this.fromData = {};
        this.isShow = 0;
      } else {
        this.message['error'](res.msg);
      }
    });
  }
  // 修改管理员信息
  updateUser() { //通过添加管理员
    let data: object = {
      userId: localStorage.getItem('userId'),
      user_id: this.fromData.userId,
      nickName: this.fromData.nickName,
      sex: this.fromData.sex,
    };
    let result = this.axios.$postData('/index/userlist/change', data);
    result.subscribe((res: any) => {
      if (res.code == 1) {
        // 子组件在调用父组件方法时，子组件必须具有该父组件方法所需要的所有参数参数
        this.getUserList();
        this.message['success'](res.msg);
        this.fromData = {};
        this.isShow = 0;
      } else {
        this.message['error'](res.msg);
      }
    });
  }
}

<!-- 添加 -->

<div class="alert_warp" (click)="colse($event)" *ngIf="isShow==1">
    <div class="alert_box">
        <header>
            <h3>{{isShow==1?"添加管理员":"编辑管理员"}}</h3>
        </header>
        <main>
            <div>
                <label for="用户名">账号:</label>
                <el-input placeholder="请输入用户名(手机号)" icon="search" [(ngModel)]="fromData.userName">
                </el-input>
            </div>
            <div>
                <label for="昵称">昵称:</label>
                <el-input placeholder="请输入昵称" icon="search" [(ngModel)]="fromData.nickName">
                </el-input>
            </div>
            <div>
                <label for="密码">密码:</label>
                <el-input placeholder="请输入密码" icon="search" [(ngModel)]="fromData.loginPass">
                </el-input>
            </div>
            <div>
                <label for="
                    性别">性别:</label>
                <el-select [(model)]="fromData.sex" [clearable]="true">
                    <el-option *ngFor="let item of [{value: '1',label: '男' },
    { value: '2', label: '女' }]" [label]="item.label" [value]="item.value">
                    </el-option>
                </el-select>
            </div>
            <div>
                <label for="
                    性别">权限:</label>
                <el-select [(model)]="fromData.power" [clearable]="true">
                    <el-option *ngFor="let item of [{value: '1',label: '超级管理员' },
    { value: '2', label: '普通管理员' }]" [label]="item.label" [value]="item.value">
                    </el-option>
                </el-select>
            </div>
            <div>
                <label for="用户名">邮箱:</label>
                <el-input placeholder="请输入安全邮箱" icon="search" [(ngModel)]="fromData.email">
                </el-input>
            </div>
        </main>
        <footer>
            <el-button size="mini" type="info" (click)="isShow=0">取消</el-button>
            <el-button size="mini" type="primary" (click)="addUser()">确认</el-button>
        </footer>
    </div>
</div>
<!-- 编辑 -->
<div class="alert_warp" (click)="colse($event)" *ngIf="isShow==2">
    <div class="alert_box">
        <header>
            <h3>{{isShow==1?"添加管理员":"编辑管理员"}}</h3>
        </header>
        <main>
            <div>
                <label for="用户名">账号:</label>
                <span>{{fromData.userName}}</span>
            </div>
            <div>
                <label for="昵称">昵称:</label>
                <el-input placeholder="请输入昵称" icon="search" [(ngModel)]="fromData.nickName">
                </el-input>
            </div>
            <div>
                <label for="
                          性别">性别:</label>
                <el-select [(model)]="fromData.sex" [clearable]="true">
                    <el-option *ngFor="let item of [{value: '1',label: '男' },
          { value: '2', label: '女' }]" [label]="item.label" [value]="item.value">
                    </el-option>
                </el-select>
            </div>
            <div>
                <label for="
                          性别">权限:</label>
                <span>{{fromData.power==1?"超级管理员":"普通管理员"}}</span>
            </div>
            <div>
                <label for="用户名">邮箱:</label>
                <span>{{fromData.email}}</span>
            </div>
        </main>
        <footer>
            <el-button size="mini" type="info" (click)="isShow=0">取消</el-button>
            <el-button size="mini" type="primary" (click)="updateUser()">确认</el-button>
        </footer>
    </div>
</div>

// vue/src/components/common/dialog.vue
<template>
  <div>
    <el-dialog title="添加管理员" :visible.sync="dialogFormVisible" width="25%" v-if="dialogFormVisible">
      <el-form :model="form">
        <el-form-item label="用户名">
          <el-input v-model="form.userName"></el-input>
        </el-form-item>
        <el-form-item label="昵称">
          <el-input v-model="form.nickName"></el-input>
        </el-form-item>
        <el-form-item label="登陆密码">
          <el-input v-model="form.loginPass"></el-input>
        </el-form-item>
        <el-form-item label="安全邮箱">
          <el-input v-model="form.email"></el-input>
        </el-form-item>
        <el-form-item label="性别">
          <el-select v-model="form.sex" placeholder="请添加系统权限">
            <el-option label="男" value="1"></el-option>
            <el-option label="女" value="2"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="权限级别">
          <el-select v-model="form.power" placeholder="请添加系统权限">
            <el-option label="超级管理员" value="1"></el-option>
            <el-option label="普通管理员" value="2"></el-option>
          </el-select>
        </el-form-item>
      </el-form>
      <button class="cancel" @click="dialogFormVisible = false">取消</button>
      <button class="reset" @click="addUser">确定</button>
    </el-dialog>
    <el-dialog
      title="编辑用户信息"
      :visible.sync="dialogFormVisible1"
      width="25%"
      v-if="dialogFormVisible1"
    >
      <el-form :model="form">
        <el-form-item label="用户名">
          <span>{{tableData.userName}}</span>
        </el-form-item>
        <el-form-item label="昵称">
          <el-input v-model="form.nickName"></el-input>
        </el-form-item>
        <el-form-item label="性别">
          <el-select v-model="form.sex" placeholder="请添加系统权限">
            <el-option label="男" value="1"></el-option>
            <el-option label="女" value="0"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="安全邮箱">
          <span>{{tableData.email}}</span>
        </el-form-item>
        <el-form-item label="权限级别">
          <span>{{tableData.power==1?"超级管理员":'普通管理员'}}</span>
        </el-form-item>
      </el-form>
      <button class="cancel" @click="dialogFormVisible1 = false">取消</button>
      <button class="reset" @click="updateUser">确定</button>
    </el-dialog>
  </div>
</template>

<script>
export default {
  data() {
    return {
      tableData: null,
      dialogFormVisible: false,
      dialogFormVisible1: false,
      form: {
        userName: "",
        nickName: "",
        loginPass: "",
        sex: "",
        email: "",
        power: ""
      }
    };
  },
  methods: {
    addUser() {
      //通过添加管理员
      let data = {
        userId: sessionStorage.getItem("userId"),
        userName: this.form.userName,
        sex: this.form.sex,
        nickName: this.form.nickName,
        loginPass: this.form.loginPass,
        email: this.form.email,
        power: this.form.power
      };
      this.$getData("/index/userlist/add", data, "post", res => {
        //					console.log(res);
        if (res.data.code == 1) {
          this.$message({
            showClose: true,
            message: res.data.msg,
            type: "success"
          });
          this.$parent.getUserList();
          this.dialogFormVisible = false;
          this.form = {};
        } else {
          this.$message({
            showClose: true,
            message: res.data.msg,
            type: "error"
          });
        }
      });
    },
    updateUser() {
      //通过添加管理员
      let data = {
        userId: sessionStorage.getItem("userId"),
        user_id: this.tableData.userId,
        nickName: this.form.nickName,
        sex: this.form.sex
      };
      this.$getData("/index/userlist/change", data, "post", res => {
        //					console.log(res);
        if (res.data.code == 1) {
          this.$message({
            showClose: true,
            message: res.data.msg,
            type: "success"
          });
          //调取父组件方法刷新列表
          this.form = {};
          this.dialogFormVisible1 = false;
          this.$parent.getUserList();
        } else {
          this.$message({
            showClose: true,
            message: res.data.msg,
            type: "error"
          });
        }
      });
    }
  }
};
</script>

<style scoped="scoped">
button {
  border: 0;
  outline: 0;
  color: #fff;
  height: 40px;
  border-radius: 3px;
}

.reset {
  background-color: rgb(64, 158, 255);
  height: 40px;
  width: 100px;
}

.cancel {
  background-color: gray;
  height: 40px;
  width: 100px;
}
</style>
